### ISSUE TITLE
add support for WORM tapes

### ISSUE THREAD

**Issue by arogge** [bareos/bareos#1781]
As a user of Bareos I would want to be able to use WORM tapes (and other read-only storages). For that we need to remove the pre-labels on not yet written volumes and instead write a normal volume label (that doesn't need to be rewritten).
While this is a change in the volume format, it will only affect empty volumes.

**Comment by rubensutter** [comment]
the manual states that there are different Pool Types in the director configuration like "*Archive" with a "Note, only Backup is currently implemented." (https://docs.bareos.org/Configuration/Director.html#directorresourcejobdefs) 

You can fiddle around with Pools and Labels to get the intended function to work but this requires to add additional Pools, Labels and Media Configurations first to then be able to write (in the configured Pool) one Label per Media but run multiple write (only) sessions on each media. I'm not sure if it's possible or would make sense to just turn the "Label Media" Option to "no" / off.

**Comment by tig987** [comment]
I used LTO WORM tapes since 2021 with Bareos versions 19, 21 and 23 without any issues.
Appending new jobs to a partially written WORM tape was also no problem so far.
