### ISSUE TITLE
Deprecate and Remove unused parameter "Allow Higher Duplicates"

### ISSUE THREAD

**Issue by arogge** [bareos/bareos#1792]
As reported by Hostedpower in [BUG1612](https://bugs.bareos.org/view.php?id=1612) parameter "Allow Higher Duplicates" seems to not do something, and grepping the code reveal just its declaration but no usage elsewhere.

Candidate for removal? 
Or the needs expressed can only be resolved with this parameter when implemented?

**Comment by jogoossens** [comment]
Still wondering if we could disallow duplicates of type incremental in general, but allow higher duplicates like full anyway.

So for example, we run incremental job hourly, if this is not finished within the hour for some reason we don't want the next incremental to run. It would potentially lead to endless incremental jobs if they would all take 1.5 hours for exemple.

However if there is a full job coming sooner or later, this is also seen as a duplicate, this job should be allowed of course or full would never run
