### ISSUE TITLE
Bareos WebUI timeout after 120 sec regardless of filetree_refresh_timeout

### ISSUE THREAD

**Issue by jogoossens** [bareos/bareos#1798]
### Bareos component version

Version 23.0.2

### Steps to reproduce

We try to restore a server with millions of files, the 120 seconds timeout is not sufficient. We were able to restore the server with 0 issues directly trough bconsole. 

However when we try the webui, we hit 120seconds timeout. We even tried https://bugs.bareos.org/view.php?id=1189 but still we hit 120s. We checked Apache ProxyTimeout and Timeout, both are at 3600.

We have no clue, but it's very frightening if we need an urgent restore and the UI doesn't work :)

### Expected results

We expect the timeout not prohibiting us from restoring a job

### Actual results

We cannot restore servers with many files because of the timeout

![backup-error](https://github.com/bareos/bareos/assets/155979277/fdb6fc21-058d-4ab8-bf0f-aa49c9d2e7a4)

### Environment

```markdown

**  /etc/bareos-webui/configuration.ini
;
; Bareos WebUI Configuration File
;
; File: /etc/bareos-webui/configuration.ini
;

;------------------------------------------------------------------------------
; SESSION SETTINGS
;------------------------------------------------------------------------------
;
[session]
; Session timeout in seconds
; Default: 3600 seconds
timeout=86400

;------------------------------------------------------------------------------
; DASHBOARD SETTINGS
;------------------------------------------------------------------------------
[dashboard]
; Autorefresh Interval in milliseconds
; Default: 60000 milliseconds
autorefresh_interval=60000

;------------------------------------------------------------------------------
; TABLE SETTINGS
;------------------------------------------------------------------------------
[tables]
; Possible values for pagination
; Default: 10,25,50,100
pagination_values=100,200,500,1000

; Default number of rows per page
; for possible values see pagination_values
; Default: 25
pagination_default_value=50

; State saving - restore table state on page reload.
; Default: false
save_previous_state=false

;------------------------------------------------------------------------------
; VARIOUS SETTINGS
;------------------------------------------------------------------------------
[autochanger]
; Name of the pool used to label and assign new media, e.g. Scratch.
; Default:
;labelpooltype=

[restore]
; Restore filetree refresh timeout in milliseconds
; Default: 120000 milliseconds
filetree_refresh_timeout=1200000

; Merge jobs on client selection
; Default: merge_jobs=true
;merge_jobs=true

; Merge filesets on client selection
; Default: merge_filesets=true
merge_filesets=false

;------------------------------------------------------------------------------
; THEME SETTINGS
;------------------------------------------------------------------------------
[theme]
; Possible values: default, sunflower
; Default: sunflower
;name=sunflower

;------------------------------------------------------------------------------
; EXPERIMENTAL FEATURES
;------------------------------------------------------------------------------
[experimental]
; Configuration resource graph
; Default:
configuration_resource_graph=true
**

```

**Comment by bruno-at-bareos** [comment]
- did you ever check you apache2 error log, did the communication was lost with php-fpm backend?
- did you check the php-fpm log engine, did the process got stopped due to php configuration parameters?
- don't you have bvfs update jobid instruction after job to pre-fill database filetree?
- did you check PostgreSQL database log that you got enough place to create the needed temp filetree?

What we know, is with fined tuned parameters it is possible to get job with over 30 millions files in filetree visible in webui.

**Comment by jogoossens** [comment]
- did you ever check you apache2 error log, did the communication was lost with php-fpm backend?
I did not see any Apache2 or php fpm timeout errors or similar, I checked apache error log, php error log and fpm error log
- did you check the php-fpm log engine, did the process got stopped due to php configuration parameters?
I did not see any Apache2 or php fpm timeout errors or similar, I checked apache error log, php error log and fpm error log
- don't you have bvfs update jobid instruction after job to pre-fill database filetree?
I have this in all job templates
	Run Script {
		RunsWhen = After
		RunsOnFailure = No
		FailJobOnError = No
		RunsOnClient = No
		console = ".bvfs_update jobid=%i"
	}

- did you check PostgreSQL database log that you got enough place to create the needed temp filetree?
It does work with bconsole and there is plenty of disk space. Also the 120s is very consistent. It really looks like some timeout hit

**Comment by jogoossens** [comment]
PS: My webui is not on the same server as the director

**Comment by bruno-at-bareos** [comment]
I hope you know that webui and director have to be the same version, right?

**Comment by jogoossens** [comment]
It's all 23.0.2 atm, just double checked :)

Most servers restore fine, it's just the ones that need long loading that are failing to restore via the web UI.

I could restore this same server 100% perfectly with bconsole, but getting the filetree there took also easily 7-10 min or something...

(Not sure if the bvsupdate does what it has to to do in all cases)

**Comment by bruno-at-bareos** [comment]
You may certainly facing a drop connection then between you bareos webui and the director if they are not on the same host: look like a firewall considering the connection as dead when it is not.

**Comment by arogge** [comment]
Let me do some guessing on that:
We have a few components that need to work together here. The browser sends a request to the WebUI, the WebUI then connects to the director and issues some BVFS commands that are supposed to return proper JSON which the WebUI would then return to back to your browser.

The error message you see in the browser sais: "Decoding failed: syntax error" which is the actual error, followed by some informational text why this might have failed (i.e. too old director or no jansson support - which is not a possible scenario in recent versions of Bareos).
So I think the WebUI fails to parse the JSON that the BVFS command returns.

Could you please
1. turn on [audit logging](https://docs.bareos.org/Configuration/Director.html#config-Dir_Director_Auditing)
2. retry what you did in the WebUI
3. check what commands the WebUI executes

Those commands should look something like this:
* .api 2 compact=yes
* .bvfs_lsdirs jobid=XX path= limit=1000 offset=0

If you then replay that using bconsole you should get something. Maybe an error or maybe malformed JSON data (which would be a bug).

**Comment by arogge** [comment]
Closing due to no response from user for 2 weeks.
