### ISSUE TITLE
fix broken tray monitor on windows

### ISSUE THREAD

**Issue by arogge** [bareos/bareos#1801]
the tray monitor is broken with the new cross-build container. Apparently `libpcre2-8-0.dll` is missing from packaging.

You can currently work around the issue by copying the DLL into your Bareos directory.
That file can be obtained from the Fedora 40 package `mingw64-pcre2-10.42-5.fc40.noarch.rpm`.

**Comment by arogge** [comment]
This will probably need to be addressed for milestones 22.1.5 and 21.1.10, too.

**Comment by kobe-highlander** [comment]
I can confirm tray-monitor starting again wit DLL manually copied.

**Comment by arogge** [comment]
If anyone is eager to try this, experimental packages from the PRs will show up here:
* [Bareos 24 (next)](https://download.bareos.org/experimental/PR-1807/windows/)
* [Bareos 23 (current)](https://download.bareos.org/experimental/PR-1817/windows/)
* [Bareos 22](https://download.bareos.org/experimental/PR-1818/windows/)
* [Bareos 21](https://download.bareos.org/experimental/PR-1819/windows/)
