### ISSUE TITLE
Nested FileSets like JobDefs

### ISSUE THREAD

**Issue by tuxmaster5000** [bareos/bareos#1854]
### Use case

Very often ‘FileSets’ only differ in small parts. This is the case, for example, when the MS-SQL add-on is used.
There, everything is the same except for the actual database. Like JobDefs which can include other JobDefs.

### Proposal

Sample config for the feature:
```
FileSet {
  Name = "Base for MS-SQL backup"
  Enable VSS = no
  Include {
    Options {
      Signature = SHA512
      Compression = GZIP9
      Accurate = pugsmc1n
      No Atime = yes
      Check File Changes = no
      Hard Links = yes
    }
}
```
```
FileSet {
  Name = "Database foo"
   FileSet = "Base for MS-SQL backup"
  Plugin = "mssqlvdi"
             ":instance=foo"
             ":database=bar"
  }
}
```
This will make the configuration much simpler.

**Comment by sebsura** [comment]
Thanks for the suggestion.  Currently we do not plan on implementing something such as this as this would complicate the configuration too much and would just lead to misunderstandings.

What you want to do can already be accomplished with the help of the `@` and `@|` operators: https://docs.bareos.org/Configuration/CustomizingTheConfiguration.html#including-other-configuration-files 

If this does not work out for you, feel free to reopen this issue.
