### ISSUE TITLE
Intgrate "SQL Server 2005 Virtual Backup Device Interface (VDI) Specification" header files into source code

### ISSUE THREAD

**Issue by tuxmaster5000** [bareos/bareos#1880]
### Use case

Until now to compile bareos for windows, you must separate download the header files for the SQL VDI interface.

### Proposal

But now Microsoft present the needed files under the MIT licence.
So  I think it will be possible to integrate it.
License text:
https://github.com/microsoft/sql-server-samples/tree/master
Header files:
https://github.com/microsoft/sql-server-samples/tree/master/samples/features/sqlvdi/include

**Comment by arogge** [comment]
That is in fact great news.
