### ISSUE TITLE
Ignore ctime/mtime of directories, but take it into account on files

### ISSUE THREAD

**Issue by EBCEEB** [bareos/bareos#1887]
### Use case

I'm trying to back up a ClickHouse instance using clickhouse-backup. It creates a directory tree and places into it hardlinks to real data files. In this case incremental backup gets all the files, because directories containig "old" files are "new".

### Proposal

I think we need something like new options for FileSet's Accurate Options to ignore directories ctime/mtime. Say add two more options `C` and `M` (in addition to `c` and `m`), and set default Accurate to `cCmMs`.

**Comment by arogge** [comment]
Hi,
we're trying to understand your use-case. Could you give us a few example directory-trees (a few files/directories will be sufficient) and how you would want them to be backed up?

Right now I think what you want to achieve will not work with Bareos.

**Comment by EBCEEB** [comment]
![clickhouse-backup-files](https://github.com/bareos/bareos/assets/11456446/8b61c623-2828-4a0e-bef1-741e0232d020)

As You can see, files (hardlinks) included into incremental (!) backup were changed at 2024-03-25, but upper directories were created today. I guess, files were included due directories date.

P.S. I want to backup hardlinked files as usual files without keeping hardlinks itself.

**Comment by arogge** [comment]
Please don't guess :smiley: 

I would also love not to guess, but for that you would have to describe what happens on your filesystem between the jobs.
The files were not included because of the directories date (because that's not a thing that Bareos does). I would guess the files were included because they did not exist in that location when the previous job ran. As such they are considered new even though their timestamps are old. This is exactly why we have accurate. Without accurate only the directory would have been picked up.

And I'm sorry, if I still don't understand your requirement. You will need to describe what change on the filesystem happens between the jobs.

**Comment by EBCEEB** [comment]
> I would guess the files were included because they did not exist in that location when the previous job ran. As such they are considered new even though their timestamps are old. This is exactly why we have accurate. Without accurate only the directory would have been picked up.

The location is the same. Directory tree is created every day, but the tree itself is always the same.
So, new directories in the old location have new inodes (and, of course, mtime and ctime), but files inside have the same inodes (ad the same ctime and mtime) and content.

**Comment by arogge** [comment]
So you have the same tree layout with new directories (i.e. the directories have new inodes) and the same files. And if I understand correctly the FileSet has `Accurate = mcs` (which is the default).
In that case it should work. Of course, it will pick up the "new" directories every time, but I guess that's not a problem.
If you could confirm your `Accurate` setting is actually `mcs`, I would try to reproduce the problem and we could then see if we can fix it.

**Comment by EBCEEB** [comment]
Accurate is unset (i.e. default - mcs), but `Signature = SHA1`

```
  Include {
    File = /home/clickhouse/backup/clickhouse/shadow
    Options {
      Signature = SHA1
    }
  }
```

**Comment by sebsura** [comment]
Could you run a backup with debug tracing with a level >= 100? I.e. before the backup do
```
setdebug level=100 client=... trace=1
```
Then the debug trace should contain lines starting with `accurate.cc`, i.e.
```
accurate-stresstest-fd (100): filed/accurate.cc:98-2 lookup <filename> ok
accurate-stresstest-fd (99): filed/accurate.cc:261-2 <filename>      st_mtime differs
```

Could you check the trace if they show that some attribute differs or if the lookup was not ok ?

**Comment by EBCEEB** [comment]
Hmm... Files have changed ctime:

```
clickhouse.*** (99): filed/accurate.cc:261-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/      st_mtime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/> ok
clickhouse.*** (99): filed/accurate.cc:261-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/      st_mtime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/> ok
clickhouse.*** (99): filed/accurate.cc:261-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/      st_mtime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/data.bin> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/data.bin      st_ctime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/columns.txt> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/columns.txt      st_ctime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/count.txt> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/count.txt      st_ctime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/default_compression_codec.txt> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/default_compression_codec.txt      st_ctime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/checksums.txt> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/checksums.txt      st_ctime differs
clickhouse.*** (100): filed/accurate.cc:98-1506 lookup </home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/data.mrk3> ok
clickhouse.*** (99): filed/accurate.cc:267-1506 /home/clickhouse/backup/clickhouse/shadow/test/product/default/all_1_1_0/data.mrk3      st_ctime differs
```

I think I know why it's happening. It's due to number of links in an inode :-(
Sorry, and thank you for help.
Will use `Accurate = ms`

**Comment by arogge** [comment]
Great you could figure it out. I didn't find the time to reproduce it yet anyway.
