### ISSUE TITLE
append.cc can't handle malformed responses

### ISSUE THREAD

**Issue by kadi315** [bareos/bareos#1921]
### Bareos component version

1. bareos-fd --version 23.0.4~pre74.8cb0a0c26 
2. bareos-sd --version 23.0.4~pre74.8cb0a0c26
3. bareos-dir --version 23.0.4~pre74.8cb0a0c26
4. bconsole --version 23.0.4~pre74.8cb0a0c26

### Steps to reproduce

1. Begin Full backup Job of a large FileSet totaling ~8,250,000 files and ~3.2TB in size. This FileSet is located on a NFS mounted filesystem on a separate client machine with hostname `pebbles-fd1` that is running the Bareos FD doing the backup Job. The Bareos Director and SD are located on the main backup server with hostname `pebbles`.

2. Allow Full backup Job to run and wait until it finishes. The SD stores backed-up data into Volume files located on a Ceph Filesystem (CephFS) named `pebblesfs` that is mounted on `pebbles` under `/mnt/pebblesfs/`. The Volumes are stored based on their Pool, which is either `Full-Pool` or `Inc-Pool`. Full Volumes are stored in `/mnt/pebblesfs/backups/Fulls/` while Incremental Volumes are stored in `/mnt/pebblesfs/backups/Incs/` The `pebblesfs` CephFS is 4PB in capacity and is located on a cluster of 6 storage servers using disk-based storage.

### Expected results

The Full backup Job should finish after running 5-7 days due to it's large size and number of files as well as limited network bandwidth. See attached `bareos_joblog.txt `for details.
[bareos_joblog.txt](https://github.com/user-attachments/files/16567788/bareos_joblog.txt)

### Actual results

The Full backup Job fails with a fatal SD error and non-fatal FD error. It will either reschedule within 20 min. to rerun after a fatal error, or continue to experience it and fail again after rescheduling and rerunning. See attached `bareos_joblog.txt `for details.
[bareos_joblog.txt](https://github.com/user-attachments/files/16567769/bareos_joblog.txt)
[bareos-fd_log.txt](https://github.com/user-attachments/files/16567770/bareos-fd_log.txt)
[ceph_log.txt](https://github.com/user-attachments/files/16567771/ceph_log.txt)
[perf_stats_block.txt](https://github.com/user-attachments/files/16567772/perf_stats_block.txt)

### Environment

```markdown
- OS:

VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```
```


### Relevant log output

```shell
Relevant logs are attached as .txt files in the actual results section. Confidential info such as IP addresses have been removed, while FQDNs have been shortened to just their hostnames. The pebbles01 server is the Ceph manager node and thus manages the storage cluster of 6 servers that host the CephFS mounted on the pebbles backup server where Bareos Volumes are located.
```

### Anything else?

Since this issue involves Bareos Volumes being stored by the SD on a mounted CephFS and seems likely related, this ticket may be relevant: https://tracker.ceph.com/issues/65073
`This can happen when FSPerfStats.re_register_queries is called before mgr/stats can process a single mds report.`

**Comment by bruno-at-bareos** [comment]
related to https://groups.google.com/u/0/g/bareos-users/c/qPaaMmC53GY

**Comment by sebsura** [comment]
It seems like the FD crashed.  Could you submit the traceback of the FD (please install debug packages and try to reproduce the crash as this helps a lot) ?

Could you also give us the fileset configuration or at least tell us which plugins you use during that backup ?

**Comment by kadi315** [comment]
Standby, the issue may not be related to Ceph. Will have some tracebacks with debug logging from the FD soon.

**Comment by arogge** [comment]
As there are no news on this one, I'm going to close it. Feel free to reopen if you can reproduce the issue.
