### ISSUE TITLE
VSS fails since last Windows-10 updates (2024-07)

### ISSUE THREAD

**Issue by tuxmaster5000** [bareos/bareos#1923]
### Bareos component version

FD: 23.0.4~pre131.d9aa41d53 

### Steps to reproduce

Start an  normal file backups using vss

### Expected results

Working backup

### Actual results

Error from the Windows OS:
```
22309: Fatal error: CreateSGenerate VSS snapshots failed. ERR=Der Vorgang wurde erfolgreich beendet (0x00000000)
22309: Error: VSS API failure calling "BackupComplete". ERR=Object is not initialized; called during restore or not called in correct sequence.
22309: Warning: VSS Writer "MSSearch Service Writer" has invalid state. ERR=The writer vetoed the shadow copy creation process during the backup preparation state.
22309: Warning: VSS Writer "Shadow Copy Optimization Writer" has invalid state. ERR=The writer vetoed the shadow copy creation process during the backup preparation state
```

### Environment

```markdown
- OS: `Windows 10` with the last 2024-7 updates
```

**Comment by tuxmaster5000** [comment]
After searching an while, it look like an Windows problem, following  the article from veritas has also helps in my case,
I have seen the same error in the windows event log.
Here the link:
https://www.veritas.com/support/en_US/article.100031121

**Comment by sebsura** [comment]
I think this is the problem:
```
MSSearch Service Writer" has invalid state. ERR=The writer vetoed the shadow copy creation process during the backup preparation state.
```

Ill close this for now.  Feel free to reopen this issue when you can prove that this is bareos misbehaving and not the various writers.
