### ISSUE TITLE
Unable to Connect to Remote Client Using Tailscale

### ISSUE THREAD

**Issue by MadMaximusJB** [bareos/bareos#1942]
### Bareos component version

1. bareos-fd: 23.0.4~pre169.6644119b5
2. bareos-dir: 23.0.4~pre169.6644119b5

### Steps to reproduce

1. Install Tailscale on both server and client.
2. Install Bareos on Debian 12. Set up with default installation method.
3. Install Bareos client on Mac running macOS Monterey 12.7.5
4. Transfer bareos-dir.conf file from Linux server to Mac client.
5. Attempt to test connection on linux server.

### Expected results

Bareos should connect to remote client using Tailscale IP and port.

### Actual results

Bareos is unable to connect to remote client using Tailscale. The firewall on the remote device allows incoming connections, and Tailscale is set to allow the connection as well. Additionally, I've enabled passive mode for the server director in regards to the client.

### Environment

```markdown
- Server OS: `Debian 12 Bookworm`
- Client OS: `macOS Monterey v12.7.5`
```

### Relevant log output

```shell
*status client=leviticus-fd
Connecting to Client leviticus-fd at xxx.xx.xx.xx:9102
Probing client protocol... (result will be saved until config reload)
Failed to connect to Client leviticus-fd.
```

```
Could not find service "org.bareos.bareos-fd" in domain for system
```
This could be the problem?^^ However, I ran commands to check if a process was using the port, and it was.

```
sudo lsof -n -iTCP:9102 | grep LISTEN

bareos-fd 9848 root    3u  IPv4 xxxxxxxxxxxxxxxxxxxx      0t0  TCP *:bacula-fd (LISTEN)
bareos-fd 9848 root    4u  IPv6 xxxxxxxxxxxxxxxxxxxx      0t0  TCP *:bacula-fd (LISTEN)
```

**Comment by pstorz** [comment]
Hello, your Issue sounds like a support request.

i would like to draw your attention to our documentation when opening a new issue, and kindly ask you to follow
what is documented there:


If you are looking for support, please check out our documentation or consider asking a question on mailing list:

https://doc.bareos.org/
https://groups.google.com/u/1/g/bareos-users
Before filling the form fields, please consider the following:

Ensure that you have searched the [existing issues](https://github.com/bareos/bareos/issues)
Read the [troubleshooting guide](https://docs.bareos.org/Appendix/Troubleshooting.html)
Read the [debugging chapter](https://docs.bareos.org/Appendix/Debugging.html)

**Comment by pstorz** [comment]
I  would suggest that you do the the setup in a local network first without VPN.
Also, you probably need to copy over the bareos-fd.conf.

**Comment by MadMaximusJB** [comment]
> Also, you probably need to copy over the bareos-fd.conf.

Would I copy that to `bareos-fd.d/client`? Or is there somewhere else that would go on the client? Thanks.

(Also, sorry, hadn't realized this was the wrong way to get support.

**Comment by bruno-at-bareos** [comment]
closing as invalid
