### ISSUE TITLE
Bareos FileDaemon (FD) Crash on Large Backup in BareosSocketTCP::write_nbytes ("stack smashing detected?")

### ISSUE THREAD

**Issue by smash0190** [bareos/bareos#1975]
### Bareos component version

The same version for each component.  Just upgraded to see if it fixes the issue but did not change anything:
23.0.4~pre219.fcc1a62ef

### Steps to reproduce

Docker images used are here:
https://hub.docker.com/u/smash0190

For example file daemon image is here:
https://hub.docker.com/r/smash0190/bareos-client

1. Starting a backup of two simultaneous large jobs (700TB).
2. Backup will run between 10hours and 2-3 days
3. File daemon crashes.
4. Backup files

### Expected results

Ideally two outcomes:
1. Bareos storage daemon and directory would be resilient to bareos file daemon crashes and would resume backup when the file daemon comes back after a crash.
2. Bareos file daemon would not crash.

### Actual results

Repeatable crashes.

### Environment

```markdown
- OS: on server (outside of docker)
23.0.4~pre219.fcc1a62ef
root@dc5590c4feb5:/# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

inside docker for all components:
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Relevant log output

```shell
Here are the details:
https://pastebin.com/rYsmgCux
```

### Relevant traces output

```shell
Part 1:
https://pastebin.com/kUTPveEN
Part 2:
https://pastebin.com/3tA2NQWc
Part 3:
https://pastebin.com/jfSiMA2n
Part 4:
https://pastebin.com/ebkDnJFt
```

### Anything else?

The above logs and traces include several examples of the crash. You can also see that small backups (<~3-5TB) work just fine.

**Comment by bruno-at-bareos** [comment]
Please attach raw log here.

**Comment by smash0190** [comment]
Ok I will monitor this more. I have not set any limits. However, if there is a memory leak or it tries to keep everything in memory I could imagine that this  would fill up. (This is just after restarting a new job). I do see the memory steadily increasing. 

Does the bareos fd keep something in memory till the end of the job? If yes I assume there is some maximum backup job size per GB of RAM?

CONTAINER ID   NAME                                     CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O   PIDS
1259cfbed0d1   backup-client-for-bareos-bareos-fd-1     100.56%   612MiB / 125.1GiB     0.48%     2.46GB / 2.05TB   0B / 0B     0


I attach the raw log files here:
[home.zip](https://github.com/user-attachments/files/17293483/home.zip)

**Comment by smash0190** [comment]
Also another note I am running the same job in parallel to two tape drives (with two different pools of tapes) to create two copies of the data (one for offsite backup). I wonder if that causes some race condition.

**Comment by smash0190** [comment]
The job causing the problems. (there are two of these running in parallel).

Job {
  JobDefs = "ArchiveOldFiles"
  Name = "Archive Old Datasets Tape Set A"
  Client = synology-nas
  FileSet = "SynologyArchive"
  Pool = ArchivePoolA
  Enabled = yes
}

Job {
  JobDefs = "ArchiveOldFiles"
  Name = "Archive Old Datasets Tape Set B"
  Client = synology-nas
  FileSet = "SynologyArchive"
  Pool = ArchivePoolB
  Enabled = yes
}
 
JobDefs {
  Name = "ArchiveOldFiles"
  Type = Backup
  Level = Full
  Client = synology-nas
  FileSet = "SelfTest"
  Storage = AutoChangerStorage
  Messages = Standard
  Pool = ArchivePoolA
  Priority = 10
  Prefer Mounted Volumes = no
  Write Bootstrap = "/var/lib/bareos/%c.bsr"
  Allow Mixed Priority = yes
  Description = "Archive old files to medium without deleting"
  Run Script {
    console = "update jobid=%i jobtype=A"
    Runs When = After
    Runs On Client = No
    Runs On Failure = No
  }
  SpoolData=Yes
  Maximum Concurrent Jobs = 4
}

FileSet {
  Name = "SynologyArchive"
  Description = "Archive Data on Synology NAS"
  Include {
    Options {
        Signature = XXH128 # calculate checksum per file
        One FS = No        # change into other filessytems
        FS Type = btrfs
        FS Type = ext2     # filesystems of given types will be backed up
        FS Type = ext3     # others will be ignored
        FS Type = ext4
        FS Type = reiserfs
        FS Type = jfs
        FS Type = vfat     # UEFIS
        FS Type = xfs
        FS Type = zfs
     }
    File = /archive
    Exclude Dir Containing = .nobackup
  }
}

**Comment by smash0190** [comment]
I have tried running with the latest „next“ version and still get a crash (24.0.0~pre1217.4a5fb0441 (11 October 2024). I attach the dump for this. Also I logged memory usage for the backup and it does not exceed the available. I attach that log as well. The log is grabbed a 1s intervals.
[home 2.zip](https://github.com/user-attachments/files/17349845/home.2.zip)
[docker-stats-logfile.log](https://github.com/user-attachments/files/17349846/docker-stats-logfile.log)

**Comment by smash0190** [comment]
Also if you look at the stats logfile memory usage seems to keep increasing. Is there something that keeps getting stored till the end of a job or is there a memory leak?

**Comment by sebsura** [comment]
It shouldnt be a memory leak. 
* Do you also expierence this behaviour on your successful backups ?
* Does the memory reset to its "idle" state once those jobs succeed ?
* In the log where the memory usage balooned to 5Gigs, over what time period are we talking about here ? Does that also take multiple days ?  You said that you grabbed it in one second intervals, does that mean it took roughly 7000 seconds, i.e. ~2 hours, for the crash to occur ?

**Comment by sebsura** [comment]
@smash0190 Are you using accurate by chance ? If so then the filedaemon has to keep the complete file list in memory during the backup.  This could explain the memory usage growth that you expierenced.

Could you maybe post your (redacted) config somewhere ?

**Comment by smash0190** [comment]
Crash
---------
Thank you for your response. I don't think the crash is related to running out of memory because it happens even with only 1.5GiB taken. The "stack smashing" crash is really my key issue right now.  I attach my complete redacted config. The job that is failing is "Archive Old Datasets Tape Set A" but I have also seen other jobs fail. I did not explicitly turn accurate on so I don't think it is on by default?
[bareos-config-setup.zip](https://github.com/user-attachments/files/17367570/bareos-config-setup.zip)
It looks like it could be some kind of race condition/locking issue but I don't know the internals of the code well enough to debut this.

I add more details on the memory below.

Memory
-----------
Yes these are typically large backups (2hours to several days and multiple terabytes). The log I posted was incrementing once a second. Regarding memory it seems that docker does not release the memory after successful backups however the actual process goes back to small. For example I just had a complete set of successful smaller backups and it is just idling but still takes up 2.439 GiB. But this does mean on the successul jobs memory usage went up to 2.4GiB.
```
CONTAINER ID   NAME                                     CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O   PIDS
357c5095e33e   backup-client-for-bareos-bareos-fd-1     0.00%     2.439GiB / 125.1GiB   1.95%     1.03GB / 951GB    0B / 0B     0
```

but if I check inside the docker it is 0% of MEM.
root@357c5095e33e:/# ps aux
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.0  0.0 1693032 6420 ?        Ssl  Oct12  36:15 /usr/sbin/bareos-fd -f

```
so I think it is releasing memory after a backup but docker maybe is lazy and doesn't remove it or something like that.

**Comment by sebsura** [comment]
Does the crash only occur if multiple jobs are run at the same time ? Do those jobs run on the same filedaemon ?

**Comment by smash0190** [comment]
In the job I posted above with the memory usage (docker stats) log it happened with just one job but I guess with the worker pool for sending it is still multi-threaded?

**Comment by smash0190** [comment]
Any ideas on how to proceed?

**Comment by sebsura** [comment]
We are currently still trying to reproduce your issue. Regarding the worker pool: neither reading the files, nor sending data to the storage daemon is currently multithreaded.  Calculating Checksums and compressing data is what the worker pool is for iirc.

I have backed up ~20TB, but did not expierence any stack issues.

Could you run the filedaemon with debug tracing enabled ? I.e. `setdebug level=200 trace=1 client=...`.
This could help track down the issue as the backtrace does not say at what point in the backup the crash occured.

**Comment by smash0190** [comment]
Ok working on this

**Comment by smash0190** [comment]
I just tested again. This time I had the job run for two days with only one job and it worked fine until other jobs started running. Once the other job on the same client started running it crashed. I attach the trace (was not able to capture the backtrace).  I don‘t think it has much useful information. Testing again with forcing only one job on that client to see if that solves the issue.
[airlab-storage.trace.2.txt](https://github.com/user-attachments/files/17694886/airlab-storage.trace.2.txt)

**Comment by sebsura** [comment]
@smash0190 Could you try if this build helps at all with your problem ? https://download.bareos.org/experimental/ssura-master-fix-race-condition-work-group/

**Comment by smash0190** [comment]
I have a big job running and it has been running successfully for 2 days by allowing only a single job on this client so I would prefer not to interrupt it. It will probably be done in about one month. I will try this release when either it fails or is successful. Thanks so much for your help.

**Comment by smash0190** [comment]
I had to restart the backup for some unrelated reason. I upgraded to the above branch and it seems like it is working with the “fix-race-condition-work-group” branch. the backup has been running in parallel for several days now without problems.
