### ISSUE TITLE
bconsole crash on windows native when trying to use command history

### ISSUE THREAD

**Issue by sebsura** [bareos/bareos#1988]
### Bareos component version

24.0.0

### Steps to reproduce

1. start bconsole
2. type ctrl + R to search the history

### Expected results

i can see the history entries

### Actual results

bconsole crashes

### Environment

```markdown
- OS: ``
- component:
```

**Comment by sebsura** [comment]
created an issue here: https://github.com/xiaozhuai/readline-win32/issues/1

**Comment by sebsura** [comment]
How should we fix this in the short run ?
* ignore it
* disable history support on msvc build
* vendor & build readline ourselves

**Comment by sebsura** [comment]
> created an issue here: [xiaozhuai/readline-win32#1](https://github.com/xiaozhuai/readline-win32/issues/1)

Maybe we should also create an issue about this on the actual readline library and/or vcpkg ?

**Comment by sebsura** [comment]
https://github.com/microsoft/vcpkg/pull/41750 this is fixed, once this pr is merged (and we rebuild with it)

**Comment by xiaozhuai** [comment]
https://github.com/microsoft/vcpkg/pull/41750 has been merged
