### ISSUE TITLE
Virtual Full S3/droplet Backup Broken Since 23.1.0 

### ISSUE THREAD

**Issue by lluuaapp** [bareos/bareos#2020]
### Bareos component version

All components upgraded to 23.1.0 (self compiled).

### Steps to reproduce

Run a S3/droplet virtual backup. The creation of a new volume fails with the error messages below. New volumes are created in the S3 bucket until the max volumes reached. Then director asks for labeling a new volume.

Same configuration works with 23.0.4 (and again after downgrading).

### Expected results

Creating virtual full backups on S3 with droplet works again.

### Actual results

Creating a new S3/droplet volume fails.

### Environment

```markdown
- OS: Everything (server and client components) on Debian 12.8.
- component: bareos-sd (most likely).
```

### Relevant log output

```shell
Nov 17 08:00:02 server bareos-dir[3128518]: bareos-sd JobId 2473: Error: Bareos cannot write on disk Volume "test-s3-000" because: The sizes do not match! Volume=0 Catalog=192
Nov 17 08:00:02 server bareos-dir[3128518]: bareos-sd JobId 2473: Error: stored/mount.cc:815 Hey!!!!! WroteVol non-zero !!!!!
```

### Anything else?

The bugfix [PR 2003](https://github.com/bareos/bareos/pull/2003) from the release notes looks suspicious to me. Maybe the difference between the initial size of the bucket (Volume=0 Catalog=192) is a hint, too?.

**Comment by lluuaapp** [comment]
Yes, using autolabeling for the S3 pool(s).

In the bucket there is a file (called 0000) that has a size of 192 bytes. Seems some kind of binary format, can read strings like "Bareos 2.0 immortal" and a date in there.

**Comment by arogge** [comment]
> In the bucket there is a file (called 0000) that has a size of 192 bytes. Seems some kind of binary format, can read strings like "Bareos 2.0 immortal" and a date in there.
Yep. That's the volume label. You should have one of these for every volume labeled in the bucket (i.e. `<volume_name>/0000`).

**Comment by arogge** [comment]
So the good news (if there is anything like good news with something like this) is that I can reproduce the problem.
For some strange reason the SD tries to determine the remote volume size (i.e. based on the chunks in the bucket) before making sure the chunks are flushed to S3.

**Comment by lluuaapp** [comment]
At least for me this is a good news. I can live with the older version for now (and I do not need to install and trace a debug version here). Thanks for looking into this so quickly!

**Comment by arogge** [comment]
As far as I can tell right now it is a simple single-line fix. The volume labeling process should `flush()` the volume when it is done writing the label. I cannot reproduce the problem anymore when this change is applied.

Would you be able and willing to try a pre-release version with a fix applied?

**Comment by lluuaapp** [comment]
Yes, you can give me a diff (or a commit) for version 23.1.0 and I will apply and test it here!

**Comment by lluuaapp** [comment]
Can confirm that this fixed the issue for me. Just backed up multiple jobs that created at least one new S3 volume. Thanks again! 💯

**Comment by arogge** [comment]
Great! Thank you for testing and thank you for the well-written report and super-quick feedback!

**Comment by dvorobiev** [comment]
> I have the change applied in [branch dev/arogge/bareos-23/issue-2020](https://github.com/bareos/bareos/tree/dev/arogge/bareos-23/issue-2020), you can also just cherry-pick the latest commit from there or wait for the [package repositories](https://download.bareos.org/experimental/arogge-bareos-23-issue-2020) to show up and install from there.

oh, thank you very much for the tip - I'm facing the same problem. before I realised to read github, I've already tried everything I can.
Your solution helped, thanks again.
