### ISSUE TITLE
CPU usage reaches 100% when creating a backup larger than 150 gigabytes

### ISSUE THREAD

**Issue by airosa-id** [bareos/bareos#2041]
### Bareos component version

1. bareos-sd --version
23.1.1~pre3.47aeb30a1
2. bareos-dir --version
23.1.1~pre3.47aeb30a1
3. mailserver-fd --version
23.1.1~pre3.47aeb30a1
4. bconsole --version
23.1.1~pre3.47aeb30a1

5. Postgresql-16

### Steps to reproduce

1. Run a Job to create a backup larger than 150Gb. (The job contains around a million files.)
2. When the archive size exceeds 150 gigabytes, the bareos-sd process starts utilizing all CPU cores (I have 8) at 100%. The network transfer speed drops to almost zero.

### Expected results

uccessful backup completion. Reasonable CPU load.

### Actual results

When the archive size exceeds 150 gigabytes, the bareos-sd process starts utilizing all CPU cores (I have 8) at 100%. The network transfer speed drops to almost zero. 
The entire virtual machine slows down drammatically but does not freeze.

when I enable tracelog 
setdebug level=200 trace=1
I received amount strings like:
27-Nov-2024 16:30:14.045925 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2

### Environment

```markdown
- OS: 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

- component:
psql --version
psql (PostgreSQL) 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
```

### Relevant traces output

```shell
7-Nov-2024 16:31:35.622608 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.622731 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.622742 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.622820 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.623962 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624020 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624126 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624149 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624238 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624261 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624365 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624423 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.624483 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.625181 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.625207 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.625445 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2                                             
27-Nov-2024 16:31:35.625516 bareos-sd (50): lib/tls_openssl_private.cc:325-0 SSL_get_error() returned error value 2
```

**Comment by bruno-at-bareos** [comment]
Hello @airosa-id unfortunately the report is incomplete to help developer or anyone else to debug your trouble.

>  SSL_get_error() returned error value 2 
is not really an error, that's the way openssl signal there's more data to come, we actually have a task to set its debug level to really higher number.

SD using more cpu can mean lot of thing, like io bound on disk (bad sector?), or less and less free space and your filesystem can't keep up with fragmentation or whatever.

You should provide, free space, configuration of the sd, joblog and trace if you can recreate them.

In the meantime, we will close this.
