### ISSUE TITLE
How to restore one file from several tapes with bextract

### ISSUE THREAD

**Issue by Ropnuk** [bareos/bareos#2045]
### Bareos component version

1. bareos-fd version: 23.1.1~pre3.47aeb30a1-149
2. bareos-dir version: 23.0.5~pre178.85426a971-136
3. bareos-sd version: 23.1.1~pre3.47aeb30a1-149
4. bareos-storage-tape version: 23.1.1~pre3.47aeb30a1-149

### Steps to reproduce

1. Backup one file on 2 tapes
2. remove storage daemon server.
3. delete info about pool and volume from catalog (info about job stay in catalog)
4. try to restore file from 2 tapes.

### Expected results

command for restore:
sudo bextract -V "AVP208L8|AVP382L8" -i include-list  /dev/st1 /Share/Restore

bextract writes first part of file from tape AVP208L8 and hung
Nothing about change tape or warnings. 

### Actual results

We have partially restored file.

### Environment

```markdown
- OS: `Ubuntu 20.04.6 (Focal Fossa)`
- component: file system on disk - XFS
```

**Comment by arogge** [comment]
So, first of all, `/dev/st1` is always the wrong device in Bareos' context. You always want to use the non-rewinding devices `/dev/nst*` or rather the stable links `/dev/tape/by-id/*-nst`.

If I remember correctly, you need to pass the Bareos Storage Device instead of the device file. With only the device file Bareos is unable to swap the volumes, as it doesn't know which autochanger to use.

**Comment by Ropnuk** [comment]
Hello,
If I try to use my autochanger I receive error:
sudo bextract -V "AVP382L8" -i include-list /dev/sch0 /Share/Restore 
29-Nov 16:55 bextract: Warning: Cannot open IPv6 stream socket. ERR=Address family not supported by protocol
29-Nov 16:55 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
29-Nov 16:55 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
bextract: stored/butil.cc:299-0 Could not find device "/dev/sch0" in config file <NULL>.
29-Nov 16:55 bextract JobId 0: Fatal error: stored/butil.cc:173 Cannot find device "/dev/sch0" in config file <NULL>.

or with generic autochanger name
sudo bextract -V "AVP382L8" -i include-list /dev/sg6 /Share/Restore
29-Nov 16:54 bextract: Warning: Cannot open IPv6 stream socket. ERR=Address family not supported by protocol
29-Nov 16:54 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
29-Nov 16:54 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
bextract: stored/butil.cc:299-0 Could not find device "/dev/sg6" in config file <NULL>.
29-Nov 16:54 bextract JobId 0: Fatal error: stored/butil.cc:173 Cannot find device "/dev/sg6" in config file <NULL>.

I tried move autochanger config file to folder ".../device", but no luck.

**Comment by bruno-at-bareos** [comment]
Hello, there's a few things that need to be clarified. First you're using an invalid mix of software, as DIR and SD have to be the same version, which is not your case
```
bareos-dir version: 23.0.5~pre178.85426a971-136
bareos-sd version: 23.1.1~pre3.47aeb30a1-149
bareos-storage-tape version: 23.1.1~pre3.47aeb30a1-149
```

You mention you remove the storage, what does that mean ? bextract needs the bareos-sd.d configuration directory to work properly (device name, etc), it might be located elsewhere than `/etc/bareos/` if you use the `-c` parameter.

Also it seems you disabled ipv6 on the system 
```
 Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
```

Which might lead you to troubles, if you don't have restricted daemon's addresses to ipv4 only 
see documentation how to do so.

Now the `bextract` usage, bextract has to be run on the SD with the attached drive, it doesn't work with autochanger so the device name has to be one of the drive of the autochanger.
You need to stop bareos-sd before trying to use bextract.

So if your tapedrive are defined like the default configuration you should run it like the following:

```
sudo bextract -V "AVP208L8|AVP382L8" -i include-list tapedrive-0 /Share/Restore
```

It should return something similar to 
```
bextract: stored/butil.cc:305-0 Using device: "tapedrive-0" for reading.
02-Dec 10:55 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST000L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:55 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:55 bextract JobId 0: Warning: stored/acquire.cc:269 Read open device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst) Volume "TST000L8" failed: ERR=backends/generic_tape_device.cc:127 Unable to open device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst): ERR=No medium found

02-Dec 10:55 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST000L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:55 bextract JobId 0: Cartridge change or "update slots" may be required.
Mount Volume "TST000L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst) and press return when ready:
```

which mean you will have to play with mtx command to load the corresponding cartridge into the correct drive.


```
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST000L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: Ready to read from volume "TST000L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
bextract JobId 0: -rw-rw-r--   1 107      107       5044094976 2024-04-28 17:15:43  /var/tmp//ioda/archives.notsaved/src/Microsoft/2022_SERVER_EVAL_x64FRE_en-us.iso
02-Dec 10:59 bextract JobId 0: End of Volume at file 2 on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst), Volume "TST000L8|TST001L8|TST002L8|TST003L8"
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST001L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: 3307 Issuing autochanger "unload slot 1, drive 0" command.
02-Dec 10:59 bextract JobId 0: Warning: stored/acquire.cc:317 Read acquire: Wrong Volume mounted on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst): Wanted TST001L8 have TST000L8
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST001L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
Mount Volume "TST001L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst) and press return when ready:
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST001L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: Ready to read from volume "TST001L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: End of Volume at file 2 on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst), Volume "TST001L8"
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST002L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: 3307 Issuing autochanger "unload slot 2, drive 0" command.
02-Dec 10:59 bextract JobId 0: Warning: stored/acquire.cc:317 Read acquire: Wrong Volume mounted on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst): Wanted TST002L8 have TST001L8
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST002L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
Mount Volume "TST002L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst) and press return when ready:
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST002L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: Ready to read from volume "TST002L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: End of Volume at file 2 on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst), Volume "TST002L8"
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST003L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 10:59 bextract JobId 0: 3307 Issuing autochanger "unload slot 3, drive 0" command.
02-Dec 10:59 bextract JobId 0: Warning: stored/acquire.cc:317 Read acquire: Wrong Volume mounted on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst): Wanted TST003L8 have TST002L8
02-Dec 10:59 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST003L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 10:59 bextract JobId 0: Cartridge change or "update slots" may be required.
Mount Volume "TST003L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst) and press return when ready:
Message from syslogd@bareos-quadstore at Dec  2 11:00:18 ...
 kernel:watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [kworker/0:7H:3721]

02-Dec 11:02 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "TST003L8" on "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 11:02 bextract JobId 0: Cartridge change or "update slots" may be required.
02-Dec 11:02 bextract JobId 0: Ready to read from volume "TST003L8" on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
02-Dec 11:02 bextract JobId 0: End of Volume at file 2 on device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst), Volume "TST003L8"
02-Dec 11:02 bextract JobId 0: End of all volumes.
02-Dec 11:02 bextract JobId 0: Releasing device "tapedrive-0" (/dev/tape/by-id/scsi-20C77B2620-nst).
1 files restored.

**Comment by Ropnuk** [comment]
Hello,
In your example there are difference only in tape drive config. 
In my case bextract restore part of file from one tape and then just stop. 
No messages about unload drive and waiting of another volume.
I'll try to change tape drive config and return with results.

**Comment by Ropnuk** [comment]
Hello. 
I've change config file for tape drive and try again. 
Unfortunately no luck. I received the same result: bextract restore file from first volume and just stop .

sudo bextract -V "AVP208L8|AVP382L8" -i include-list1  "drive2_RND2" /Share/Restore
05-Dec 11:16 bextract: Warning: Cannot open IPv6 stream socket. ERR=Address family not supported by protocol
05-Dec 11:16 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
05-Dec 11:16 bextract: Warning: Can't add default IPv6 address (IPv6 address wanted but IPv6 is disabled!)
bextract: stored/butil.cc:305-0 Using device: "drive2_RND2" for reading.
05-Dec 11:16 bextract JobId 0: No slot defined in catalog (slot=0) for Volume "AVP208L8" on "drive2_RND2" (/dev/tape/by-id/scsi-1174FA5065-nst).
05-Dec 11:16 bextract JobId 0: Cartridge change or "update slots" may be required.
05-Dec 11:16 bextract JobId 0: Ready to read from volume "AVP208L8" on device "drive2_RND2" (/dev/tape/by-id/scsi-1174FA5065-nst).
bextract JobId 0: -rwxrwx---   1 KL^svc_a winbindd 95481236992 2023-11-13 18:40:51  /Share/Restore/Share/TFS_DB/Nov_13_2023__6-17PMConfiguration.bak

**Comment by Ropnuk** [comment]
Hello, last question: where I can find bextract logs? Maybe in logs I'll find the root cause of problem.

**Comment by arogge** [comment]
`bextract` logs to stdout/stderr. If you need debugging you can pass `-d <debuglevel>` with 50 for some information and 1000 for basically anything that is logged.
