### ISSUE TITLE
[bareos-restapi] restore job before parameter does not accept time value

### ISSUE THREAD

**Issue by WhiskyLe** [bareos/bareos#2052]
### Bareos component version

bareos-fd --version
23.1.1~pre3.47aeb30a1
bareos-dir --version
23.1.1~pre3.47aeb30a1
 bareos-sd --version
23.1.1~pre3.47aeb30a1
bconsole --version
23.1.1~pre3.47aeb30a1

### Steps to reproduce

create any restore job trough the api (POST: /control/jobs/restore)
in the before parameter put a date time value "2024-12-06 23:59:59"
quick fix would be to escape the space with a double backslash

an example job:
{
    "jobControl": {
        "client": "srvptest-rz1-1-fd",
        "where": "/tmp/bareos-restores",
        "storage": "RZ1-FileStorage1",
        "restorejob": "RestoreFiles",
        "fileset": "PerconadumpSet",
        "before": "2024-12-06 23:59:59",
        "replace": "always",
        "restoreclient": "srvtest-rz1-a-fd",
        "priority": "10",
        "selectAllDone": "yes",
        "file": "</tmp/test"
    }
}

### Expected results

{
    "jobid": xxxx
}

### Actual results

{
    "message": "Could not start job 'restore client=srvptest-rz1-1-fd where=/tmp/bareos-restores storage=RZ1-FileStorage1 restorejob=RestoreFiles fileset=PerconadumpSet replace=always restoreclient=srvtest-rz1-a-fd file=</tmp/test before=2024-12-06 23:59:00 select all done' on director bareos-dir. Message: 'failed: Unknown keyword: 23:59:00\n'"
}

### Environment

```markdown
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
```

**Comment by bruno-at-bareos** [comment]
You should escape the mandatory double quotes around when value.

do you tried already \"2024-12-22 22:22:22\" ?
