### ISSUE TITLE
bareos database update fails if dbport is not default

### ISSUE THREAD

**Issue by jmahmens** [bareos/bareos#2060]
### Bareos component version

1. bareos-dir 23.1.1~pre3.47aeb30a1-149 or older (found on debian bullseye)

### Steps to reproduce

running database (psql) not at default port 5432 (5433 in this case)
update bareos-system from 23.1.1~pre3.47aeb30a1-149 to24.0.0~pre1543.d66bd14a5-4

### Expected results

bareos-dir works after update

### Actual results

bareos-dir stops with fatal error:

### Environment

```markdown
- OS: `debian bullseye`
- database `psql on port:5433` (default:5432)
```

### Relevant log output

```shell
2024-12-13 10:37:19 bareos-dir ERROR TERMINATION
Please correct the configuration in /etc/bareos/bareos-dir.d/*/*.conf
2024-12-13 10:44:38 bareos-dir JobId 0: Fatal error: Version error for database "bareos". Wanted 2240, got 2230
2024-12-13 10:44:38 bareos-dir JobId 0: Fatal error: Could not open Catalog "MyCatalog", database "bareos": Version error for database "bareos". Wanted 2240, got 2230
```

### Anything else?

I have solved this for me by changing **update_bareos_tables** and **bareos-config-lib.sh** and adds the _dbport_.
This may be an example and ther are more places to add the Database port
[bareos-update.zip](https://github.com/user-attachments/files/18125211/bareos-update.zip)

**Comment by bruno-at-bareos** [comment]
Do you missed the information (documented) that those scripts support PG ENV variable to support those kind of case ?

Could you retry/reproduce by setting the PG ENV vars ?

**Comment by jmahmens** [comment]
Sorry for late reply.
Export the PGPORT wont work for me, because there are more than one psql instances running on different ports.
Setting this will block the other instance for access.
Now the answers from the last questions:
This happens alway on Updates from apt and i have to call update_bareos_table manualy after update fails.
The Catalog resource is configure normaly with the dbport = 5433 as extra entry.
